add a bunch of stuff

diff --git a/src/bin/iot b/src/bin/iot
--- a/src/bin/iot
+++ b/src/bin/iot
@@ -9,60 +9,67 @@
 #            - Style, function names, etc
 #            - Usage output
 
-PROG="$(basename "$0")";
-readonly PROG; export PROG
-
-# DEBUG
-: "${SNAP:=$PWD}";
-readonly SNAP; export SNAP
-
-: "${SNAP_USER_COMMON:="${PWD}/data"}";
-readonly SNAP_USER_COMMON; export SNAP_USER_COMMON
-
 print_usage() {
 	echo "IDIoT (Interactive Devtools for IoT)"
 	echo
-	echo "usage: ${PROG} [subcommand]"
+	echo "USAGE: ${PROG} [subcommand]"
 	echo
 	echo "SUBCOMMANDS"
-	for _cmd in $_commands; do
+	for _cmd in $COMMANDS; do
 	  _cmd_name="$(basename "$_cmd")"; _cmd_name="${_cmd_name#iot-}"
 		printf '%8s    %s\n' "${_cmd_name}" "$("${_cmd}" description)"
 	done | sort
+	alias_warning
 } >&2
 
-process_builtins() {
-	case "$_arg" in
-		help)
-			# shellcheck disable=SC2016
-			{
-				echo 'This program is meant to be used in the following way:'
-				echo '  iot() { eval $(idiot "$@"); }'
-				echo
-				print_usage
-				return 1
-			} >&2
-			;;
-	esac
+alias_warning() {
+	# shellcheck disable=SC2016
+	[ "${IDIOT_WARNING:-}" != "0" ] || {
+		echo
+		echo '-------------------------------------------------------------------------'
+		echo
+		echo 'NOTE: This program is meant to be used in the following way:'
+		echo '  iot() { eval $(idiot "$@"); }'
+		echo
+		echo 'You can disable this warning by setting IDIOT_WARNING=0 in your environment.'
+	} >&2
 }
 
 process_commands() {
-	for _cmd in $_commands; do
+	{ [ "$_arg" != "help" ]; } ||
+		return 0
+
+	for _cmd in $COMMANDS; do
 	  _cmd_name="$(basename "$_cmd")"
 
-	  [ "iot-${_arg}" != "$_cmd_name" ] ||
-			exec "${_cmd}" "$@"
+	  [ "iot-${_arg}" = "$_cmd_name" ] ||
+	  	continue
+
+	  # shellcheck disable=SC2063
+		exec "${_cmd}" "$@"
   done
+
+	echo "err: command '${_arg}' not found." >&2
+	echo >&2
 }
 
 main() {
-	_commands="$(find "${SNAP}/bin" -maxdepth 1 -executable -name 'iot-*')"
+	set -eu
+
+	PROG="$(basename "$0")";
+	export PROG
+
+	: "${IDIOT_BIN:=/usr/bin}"
+	: "${IDIOT_DATA_ROOT:=${XDG_DATA_HOME:-${HOME}/.local/share}}"
+	export IDIOT_DATA_ROOT
+
+	COMMANDS="$(find "${SNAP}/bin" -maxdepth 1 -executable -name 'iot-*')"
 
 	_arg="${1:-help}"
-	shift || true
+	[ "$#" -eq 0 ] ||
+		shift
 
-	# Process builtins
-	process_builtins "$@"
+	export IDIOT_DATA="${IDIOT_DATA_ROOT}/${_arg}"
 	process_commands "$@"
 
 	print_usage
